# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb9abc890f652705b7cf3db2b67190a5f636f2ec8467d4739ecf365a3f082419a565449efa8221fc48b56068cbd2edc03d977a7c8e65ca132b5f00cdb78c20eb

test:
  secret_key_base: 40f38fde3e5b5cec15d120f5c01289995bbb43e69cfe74a9072684f530f0e64b145e2c47d5844521c9c1dec5b6f35edc6977151d32043c3fa48429d4791254bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
